### ISSUE TITLE
Can't comment an issue without closing it!

### ISSUE THREAD

**Issue by TheNiska** [TheNiska/MainWebSite#3]

**Comment by Kropanov** [comment]
Can't you comment on issues without closing or what?

**Comment by TheNiska** [comment]
Yes

**Comment by Kropanov** [comment]
It's really weird! I can do this. Don't know why you're not able to comment...

**Comment by Kropanov** [comment]
If the repository owner on GitHub is unable to comment on an issue, there could be several possible reasons for this limitation:

Access restrictions: The repository owner may have access restrictions or permissions that prevent them from commenting on issues. In this case, the owner can try updating the access settings or request the project administrator to modify the access permissions.

Technical issues: Occasionally, there may be temporary technical issues on GitHub that can cause problems with the commenting functionality. In such cases, it is recommended to refresh the page, clear the browser cache, or try using a different browser.

Violation of rules and restrictions: If the repository owner has violated the rules or restrictions of the GitHub platform, it could result in a temporary or permanent limitation on their ability to comment. In such situations, it is advisable to contact GitHub support to understand the reasons and explore possible solutions.

If the repository owner is facing the issue of being unable to comment on issues in their repository, it is recommended to consult the GitHub documentation, check the access and permission settings in the repository, and contact GitHub support for further assistance in resolving the problem.

**Comment by TheNiska** [comment]
Yeah, I know. I read it too, but nothing helps.

**Comment by TheNiska** [comment]
By the way I found out that I can comment from my phone :)

**Comment by TheNiska** [comment]
Anyway thank you. I think I can close the issue now.
